name: Lego Price Tracker

permissions:
  contents: write

# Déclencheurs : 
on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *'

# Tâches : 
jobs:
  run-tracker:
    # La machine virtuelle sur laquelle le script va tourner
    runs-on: ubuntu-latest
    steps:
      # Récupérer le code du dépôt
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Config and Commit Changes
        run: |
          pip install pandas openpyxl requests beautifulsoup4
          python config_generator.py
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add config_sets.xlsx *.txt
          if ! git diff --cached --quiet; then
            git commit -m "feat(config): Automatically update sets from .txt files"
            git push
          else
            echo "No new set configuration to commit."
          fi

      # Configurer Chrome pour Selenium
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1

      # Configurer Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Installer les librairies nécessaires
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Lancer le script Python
      - name: Run Lego Price Tracker
        id: run_script
        env:
          GMAIL_ADDRESS: ${{ secrets.GMAIL_ADDRESS }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          MAIL_DESTINATAIRE: ${{ secrets.MAIL_DESTINATAIRE }}
        run: python catch_lego_price.py

      # Commit du fichier Excel
      - name: Commit and push if changed
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add prix_lego.xlsx
          git diff-index --quiet HEAD || git commit -m "Update price data" && git push

      - name: Generate and push Wiki
        run: python generer_wiki.py
        env:
          GIT_USER: "github-actions[bot]"
          GIT_EMAIL: "github-actions[bot]@users.noreply.github.com"
          WIKI_URL: https://x-access-token:${{ secrets.PAT }}@github.com/${{ github.repository }}.wiki.git