name: Lego Tracker Workflow

permissions:
  contents: write

on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *' # Votre heure de lancement

jobs:
  # On n'a plus qu'un seul et unique job qui fait tout dans l'ordre
  build-and-update:
    name: Scrape Prices, Deals and Update Wiki
    runs-on: ubuntu-latest
    steps:
      # --- ÉTAPE 1 : PRÉPARATION ---
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install All Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # --- ÉTAPE 2 : EXÉCUTION DES SCRIPTS DE COLLECTE ---
      # On exécute tous les scripts qui modifient les fichiers de données

      - name: Run Config Generator
        run: python config_generator.py

      - name: Run Avenue de la Brique Scraper
        run: python avenue_scraper.py
      
      - name: Run Deal Hunter (Promotions)
        env:
          GMAIL_ADDRESS: ${{ secrets.GMAIL_ADDRESS }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          MAIL_DESTINATAIRE: ${{ secrets.MAIL_DESTINATAIRE }}
        run: python deal_hunter.py

      - name: Run Main Price Tracker
        env:
          GMAIL_ADDRESS: ${{ secrets.GMAIL_ADDRESS }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          MAIL_DESTINATAIRE: ${{ secrets.MAIL_DESTINATAIRE }}
        run: python catch_lego_price.py

      # --- ÉTAPE 3 : COMMIT UNIQUE DE TOUS LES CHANGEMENTS DE DONNÉES ---
      # On rassemble ici TOUS les changements de TOUS les scripts précédents
      - name: Commit data files changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          # On ajoute tous les fichiers de données potentiellement modifiés ou supprimés
          git add config_sets.xlsx prix_lego.xlsx deals_du_jour.json deals_vus.json *.txt
          
          # On commite seulement s'il y a des changements à commiter
          if ! git diff --cached --quiet; then
            git commit -m "Update price, config and deal data"
            git push
          else
            echo "No data changes to commit."
          fi

      # --- ÉTAPE 4 : GÉNÉRATION ET PUSH DU WIKI ---
      # Cette étape ne se lance qu'après que les données ont été sauvegardées
      - name: Generate and push Wiki
        run: python generer_wiki.py
        env:
          # On utilise le PAT pour s'assurer d'avoir les droits d'écriture sur le wiki
          WIKI_URL: https://x-access-token:${{ secrets.PAT }}@github.com/${{ github.repository }}.wiki.git
          GIT_USER: "github-actions[bot]"
          GIT_EMAIL: "41898282+github-actions[bot]@users.noreply.github.com"